on:
  workflow_call:
    # inputs:
    #   environment:
    #     type: string
    #     description: enter env
jobs:
  test_call:
    environment: "${{ github.ref_name }}"
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo HELP: ${{ vars.HELP }}
         echo ONLY_MAIN: ${{ vars.ONLY_MAIN}}