on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: enter env
jobs:
  test_call:
    environment: "${{ inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.help }}
