on:
  workflow_dispatch:
    


  
jobs:

  testing:
    environment: "${{ github.ref_name }}"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"

  test_call:
    uses: ./.github/workflows/test_call.yml
 
